In [23]:
import numpy as np
from PIL import Image

In [53]:
# img = Image.open("./assets/plane.png")
# R = np.array(img)[:,:,0]
R = np.array([
    [1,2,3,7],
    [12,14,25,31],
    [9,4,3,22],
    [2,1,5,90]
    ], dtype=np.float64)

Us, Ss, Vts = np.linalg.svd(R)
print("Us:\n", Us)
print("Ss:\n", Ss)
print("Vts:\n", Vts)

Us:
 [[-0.07584099 -0.08528297  0.07908183 -0.9903136 ]
 [-0.36305855 -0.8992      0.21145449  0.12212634]
 [-0.23223517 -0.13874352 -0.96156285 -0.04705252]
 [-0.8991682   0.40609901  0.1563008   0.04637019]]
Ss:
 [99.48881387 27.67586817  6.69336097  0.47027192]
Vts:
 [[-0.08363751 -0.07098899 -0.14571018 -0.98322626]
 [-0.40873791 -0.46640781 -0.76317694  0.18154346]
 [-0.85531445 -0.08537177  0.51101729  0.00318991]
 [ 0.30720558 -0.87757392  0.36768305 -0.01726051]]


In [25]:
R = np.array(R, dtype=np.float64)

In [26]:
def matrix_to_img(R):
    full = np.empty((R.shape[0], R.shape[1], 3), dtype=np.uint8)
    full[:, :, 0] = R
    full[:, :, 1] = 0
    full[:, :, 2] = 0
    img = Image.fromarray(full)
    img.save('./assets/reduced.png')

In [27]:
matrix_to_img(R)

In [28]:
R.ndim

2

In [29]:
R.shape

(4, 4)

In [30]:
R.dtype

dtype('float64')

In [31]:
R.T.shape

(4, 4)

In [32]:
R.T.ndim

2

In [33]:
AtA = R.T @ R
AtA.shape

(4, 4)

In [34]:
n = AtA.shape[0]

In [35]:
AtA

array([[ 230.,  208.,  340.,  757.],
       [ 208.,  217.,  373.,  626.],
       [ 340.,  373.,  668., 1312.],
       [ 757.,  626., 1312., 9594.]])

In [36]:
matrix_to_img(AtA)

In [37]:
for i in range(n):
    for j in range(n):
        assert AtA[i,j] == AtA[j,i]

In [38]:
assert np.allclose(AtA.T, AtA)

In [119]:
eigenValues, eigenVectors = np.linalg.eig(AtA)

In [120]:
eigenVectors

array([[ 0.08363751,  0.40873791, -0.85531445,  0.30720558],
       [ 0.07098899,  0.46640781, -0.08537177, -0.87757392],
       [ 0.14571018,  0.76317694,  0.51101729,  0.36768305],
       [ 0.98322626, -0.18154346,  0.00318991, -0.01726051]])

In [121]:
eigenValues

array([9.89802408e+03, 7.65953679e+02, 4.48010810e+01, 2.21155674e-01])

In [122]:
idx = eigenValues.argsort()[::-1]

In [123]:
idx

array([0, 1, 2, 3])

In [124]:
eigenValuesSorted = eigenValues[idx]

In [125]:
eigenValuesSorted

array([9.89802408e+03, 7.65953679e+02, 4.48010810e+01, 2.21155674e-01])

In [126]:
eigenVectorsSorted = eigenVectors[:,idx]

In [127]:
eigenVectorsSorted

array([[ 0.08363751,  0.40873791, -0.85531445,  0.30720558],
       [ 0.07098899,  0.46640781, -0.08537177, -0.87757392],
       [ 0.14571018,  0.76317694,  0.51101729,  0.36768305],
       [ 0.98322626, -0.18154346,  0.00318991, -0.01726051]])

In [128]:
Vts

array([[-0.08363751, -0.07098899, -0.14571018, -0.98322626],
       [-0.40873791, -0.46640781, -0.76317694,  0.18154346],
       [-0.85531445, -0.08537177,  0.51101729,  0.00318991],
       [ 0.30720558, -0.87757392,  0.36768305, -0.01726051]])

In [75]:
VSorted.T[:,[0]]

array([[ 0.30720558],
       [-0.85531445],
       [ 0.40873791],
       [ 0.08363751]])

In [76]:
Vts[:,[3]]

array([[-0.98322626],
       [ 0.18154346],
       [ 0.00318991],
       [-0.01726051]])

In [109]:
m = R.shape[0]
m

4

In [110]:
import math
Singulars = [math.sqrt(x) for x in eigenValuesSorted if x > 0]
Singulars

[99.48881386585735, 27.675868168262394, 6.69336096615802, 0.47027191546013386]

In [116]:
U = np.zeros((m,m), dtype=np.float64)
U

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [118]:
for i in range(m):
    try:
        sing = Singulars[i]
        v = eigenVectorsSorted[:,[i]]
    except IndexError:
        break
    col = (1/sing) * np.dot(R, v)
    print(col)
    print(col.shape)
    print(col.ndim)
    U[:,[i]] = col
U

[[0.07584099]
 [0.36305855]
 [0.23223517]
 [0.8991682 ]]
(4, 1)
2
[[ 0.08528297]
 [ 0.8992    ]
 [ 0.13874352]
 [-0.40609901]]
(4, 1)
2
[[ 0.07908183]
 [ 0.21145449]
 [-0.96156285]
 [ 0.1563008 ]]
(4, 1)
2
[[-0.9903136 ]
 [ 0.12212634]
 [-0.04705252]
 [ 0.04637019]]
(4, 1)
2


array([[ 0.07584099,  0.08528297,  0.07908183, -0.9903136 ],
       [ 0.36305855,  0.8992    ,  0.21145449,  0.12212634],
       [ 0.23223517,  0.13874352, -0.96156285, -0.04705252],
       [ 0.8991682 , -0.40609901,  0.1563008 ,  0.04637019]])